name: Compile PDF

on:
  
  push:
    # branches: [ master ]
    tags:
      - '*'

  
  workflow_dispatch:


jobs:
  
  build_pdf:
    
    runs-on: ubuntu-latest

    
    steps:
      
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Get tag name
        uses: little-core-labs/get-git-tag@v3.0.1
        id: tagName

      - name: Test tag name
        run: |
          echo "This is a test"
          echo "Tag is ${GITHUB_REF##*/}"
          echo "${{steps.tagName.outputs.tag }}"
          echo "$GIT_TAG_NAME"

      # - name: Compile Latex Document
      #   uses: xu-cheng/latex-action@v2
      #   with:
      #     root_file: report.tex

      # - name: Publish PDF
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: report.pdf
      #     tag_name: 0.0.2
