name: Compile PDF

on:
  
  push:
    branches: [ master ]

  
  workflow_dispatch:


jobs:
  
  build_pdf:
    
    runs-on: ubuntu-latest

    
    steps:
      
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Get version tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Compile Latex Document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: report.tex

      - name: Publish PDF
        uses: softprops/action-gh-release@v1
        with:
          files: report.pdf
          tag_name: $RELEASE_VERSION